"""
Synthetic demo dataset for the Customer Feedback Theme Extractor.
Covers reviews, survey responses and support tickets across several themes.
"""

import json
import csv
import io
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

DEMO_FEEDBACK = [
    # ---- Onboarding / Setup ----
    {"type": "review",   "text": "Setting up the product took way longer than expected. The documentation is confusing and I had to contact support twice just to get started."},
    {"type": "survey",   "text": "The onboarding flow is overwhelming. There are too many steps and no clear explanation of what each step does."},
    {"type": "support",  "text": "Hi, I cannot figure out how to connect my data source during the initial setup. The wizard keeps throwing an error on step 3."},
    {"type": "review",   "text": "Onboarding was a mess. I spent half a day just trying to import my CSV files. Needs a much simpler getting-started guide."},
    {"type": "survey",   "text": "Initial configuration was painful. Would love a short video walkthrough or an interactive tutorial."},
    {"type": "review",   "text": "Once I figured out the setup it was fine, but the learning curve in the first hour is really steep."},

    # ---- Performance / Speed ----
    {"type": "review",   "text": "The dashboard takes over 10 seconds to load when I have more than 500 records. This is unacceptable for a paid product."},
    {"type": "support",  "text": "Queries are timing out on large datasets. Our dataset has about 50k rows and the analysis never completes."},
    {"type": "survey",   "text": "Performance is the biggest issue for me. Loading times make it hard to iterate quickly on the analysis."},
    {"type": "review",   "text": "Love the features but the app is just slow. Everything lags, especially the chart rendering."},
    {"type": "support",  "text": "File upload stalls at 70% for large Excel files. Is there a file size limit I'm not aware of?"},
    {"type": "survey",   "text": "Please optimize the backend. The sentiment analysis step alone takes 5+ minutes for a modest dataset."},

    # ---- UI / Design ----
    {"type": "review",   "text": "The UI is clean and intuitive. I love the color coding for sentiment — it makes it super easy to spot negative themes at a glance."},
    {"type": "survey",   "text": "Really polished interface! The theme cards are visually appealing and easy to navigate."},
    {"type": "review",   "text": "Great design overall. The dashboard layout makes sense and the charts are clear. Minor complaint: the font is a bit small on mobile."},
    {"type": "survey",   "text": "The design feels modern and professional. Impressed by how well everything is organized."},
    {"type": "review",   "text": "I appreciate the dark mode option. Spent hours in the tool and my eyes didn't get tired."},
    {"type": "survey",   "text": "Beautiful UI but the mobile experience needs work. Some buttons overlap on smaller screens."},

    # ---- Accuracy / AI Quality ----
    {"type": "review",   "text": "The theme extraction is surprisingly accurate. It correctly grouped feedback about shipping delays even when customers phrased it very differently."},
    {"type": "survey",   "text": "Impressed by the AI — the sentiment labels are almost always correct. Only a few edge cases where sarcasm was misclassified."},
    {"type": "support",  "text": "The theme names generated by the AI are sometimes too generic, like 'Product Issues'. Can I customise them?"},
    {"type": "review",   "text": "Sentiment analysis works well for straightforward feedback but struggles with mixed or nuanced reviews."},
    {"type": "survey",   "text": "The clusters are very logical and the representative quotes chosen are spot-on."},
    {"type": "review",   "text": "The recommendations section is where the AI really shines — very actionable and prioritized correctly."},

    # ---- Pricing / Value ----
    {"type": "review",   "text": "It's expensive for small teams. A lower-tier plan with fewer monthly analyses would make it accessible to startups."},
    {"type": "survey",   "text": "The pricing is not transparent. I only discovered the per-analysis charge after my first bill was higher than expected."},
    {"type": "review",   "text": "Good value for the price if you're an enterprise. Not so much for individuals or small businesses."},
    {"type": "support",  "text": "I accidentally ran the analysis three times on the same dataset and got billed for each run. Can I get a refund?"},
    {"type": "survey",   "text": "Would love a free tier or a trial that doesn't require a credit card."},
    {"type": "review",   "text": "Price is reasonable compared to hiring a data analyst, especially for monthly feedback reviews."},

    # ---- Integrations ----
    {"type": "review",   "text": "The Zapier integration is a game-changer. Feedback flows in automatically from our Typeform surveys."},
    {"type": "survey",   "text": "I wish there was a direct Slack integration so I could get theme summaries posted to our product channel."},
    {"type": "support",  "text": "The Google Sheets connector keeps disconnecting after a few hours. I have to re-authenticate every day."},
    {"type": "review",   "text": "Native Salesforce integration works perfectly. Pulling in support tickets is seamless."},
    {"type": "survey",   "text": "Would love a Notion integration to push reports directly to our workspace."},
    {"type": "review",   "text": "REST API is well-documented. We built our own integration in a day. Great for developers."},

    # ---- Export / Reporting ----
    {"type": "review",   "text": "The PDF report is excellent — I can share it directly with stakeholders without any extra formatting."},
    {"type": "survey",   "text": "Would be useful to have a PowerPoint export option for executive presentations."},
    {"type": "support",  "text": "The CSV export is missing the sentiment column. Can you add it in the next update?"},
    {"type": "review",   "text": "Automated weekly reports sent to email would save me a lot of time."},
    {"type": "survey",   "text": "The report layout is professional. My manager was impressed and asked what tool we were using."},
    {"type": "review",   "text": "Charts in the PDF are crisp and clear. The color coding matches the dashboard, which is a nice touch."},
]


def get_demo_feedback_list():
    """Return the demo feedback as a list of unified schema dicts."""
    return [
        {
            "feedback_id": f"demo_{i}",
            "source_file": f"{item['type']}_demo.json",
            "raw_text": item["text"],
        }
        for i, item in enumerate(DEMO_FEEDBACK)
    ]


def write_demo_files(upload_dir: Path):
    """
    Write demo data into the upload directory as CSV files grouped by type.
    Clears any existing files first.
    """
    upload_dir.mkdir(exist_ok=True)

    # Remove existing files
    for f in upload_dir.iterdir():
        if f.is_file():
            f.unlink()

    # Group by type
    groups: dict[str, list] = {}
    for item in DEMO_FEEDBACK:
        groups.setdefault(item["type"], []).append(item["text"])

    for ftype, texts in groups.items():
        file_path = upload_dir / f"{ftype}_demo.csv"
        with open(file_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=["feedback"])
            writer.writeheader()
            for text in texts:
                writer.writerow({"feedback": text})

    logger.info(
        f"Demo dataset written: {sum(len(v) for v in groups.values())} entries across {len(groups)} files"
    )
    return list(upload_dir.iterdir())